<?php
/** @var $this Doofinder_Feed_Block_Banner */
$banner = $this->getBanner();
?>

<?php if($banner !== null): ?>
    <div id="doofinder-banner" class="doofinder-banner">
        <a href="<?php /* @escapeNotVerified */ echo $banner['link']; ?>"
            <?php /* @escapeNotVerified */ echo $banner['blank'] ? 'target="_blank"' : ''; ?>>
            <img alt="Doofinder Banner" src="<?php /* @escapeNotVerified */ echo $banner['image']; ?>" />
        </a>
    </div>
    <script>
        new doofinderBanner(
            '<?php echo $this->getAjaxUrl() ?>',
            '<?php echo $banner['id'] ?>',
            'doofinder-banner',
            '<?php echo $this->getBannerPlacement() ?>'
        );
    </script>
<?php endif; ?>
